default:
  image: ruby:2.4.2
  before_script:
    - cd reddit
    - bundle install

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongo'

build_job:
  stage: build
  script:
    - echo 'Building'

reddit_run:
  stage: build
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  image: r2d2k/otus-reddit:1.0
  before_script:
    - echo 'Preparing to run reddit'
  script:
    - echo 'Run reddit'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch_review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - main

staging:
  stage: stage
  when: manual
  only:
    - tags
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - tags
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
