apiVersion: apps/v1
kind: Deployment	# Deploy metadata
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:			# Deploy specification
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
      release: {{ .Release.Name }}
  template:		# Pod description
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: ui
        ports:
          - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
